### ISSUE TITLE
A3: check point 1 issue

### ISSUE THREAD

**Issue by Khensura21** [joeyklee/quant-humanists-2019#11]
after adding the below code to index.js file and running  `npm run dev`, I am still not getting the p5 sketch

`function setup(){
    createCanvas(400, 400)

}

function draw(){    
    background(200);
    ellipse(mouseX, mouseY, 50, 50);

}`

**Comment by Khensura21** [comment]
ERROR message:

<img width="1005" alt="screen shot 2019-02-19 at 11 16 27 pm" src="https://user-images.githubusercontent.com/43118650/53066149-8ad0e800-349c-11e9-969c-83a652171269.png">

**Comment by joeyklee** [comment]
Hi @Khensura21 - looks like you tired to go to the URL: index.js

If you do the following:

Terminal Window:
```
npm start
```

then go to your web browser:

at the URL: http://localhost:3030

Does your page show?

**Comment by Khensura21** [comment]
No, the page still doesn't show what it is expected.

**Comment by joeyklee** [comment]
Hm, and you're editing the `/public/index.js` file?

It would be helpful to see it in context. E.g. if you have a repository on Github OR if you can make a screenshot of where you're editing. There are multiple index.js files in the project.

**Comment by Khensura21** [comment]
maybe that is the problem, the index file I am editing is not in the public folder. It is in the src folder. 


<img width="671" alt="screen shot 2019-02-19 at 11 35 27 pm" src="https://user-images.githubusercontent.com/43118650/53066751-38dd9180-349f-11e9-801d-1aa06c617a03.png">

**Comment by joeyklee** [comment]
Yes that will definitely break your entire application. I would suggest getting the code from the original project for `src/index.js` and putting it back in. Or re-running the `generate feathers app` since you're still early on in the process.

**Comment by Khensura21** [comment]
So, to be clear,  put that particular index.js file circled below into the "public" folder? Because I just  re-ran the generate feathers app and it showed up in the exact same spot

<img width="662" alt="screen shot 2019-02-19 at 11 50 44 pm" src="https://user-images.githubusercontent.com/43118650/53067243-5ad81380-34a1-11e9-93a9-e6b577aef858.png">

**Comment by joeyklee** [comment]
Notice how this project is structured: 
+ https://github.com/joeyklee/my-data-feelings

<img width="480" alt="screen shot 2019-02-19 at 23 54 46" src="https://user-images.githubusercontent.com/3622055/53067381-f2d5fd00-34a1-11e9-9e24-085f19b45428.png">
<img width="550" alt="screen shot 2019-02-19 at 23 54 51" src="https://user-images.githubusercontent.com/3622055/53067382-f2d5fd00-34a1-11e9-9d9f-91d96e9a57b0.png">

**Comment by Khensura21** [comment]
I got it. Although I don't know why the feathers background is also showing. Is that suppose to be that way?

<img width="1195" alt="screen shot 2019-02-20 at 12 03 48 am" src="https://user-images.githubusercontent.com/43118650/53067645-16e60e00-34a3-11e9-8146-2519ac2c2671.png">

**Comment by joeyklee** [comment]
You can remove all the other irrelevant HTML/CSS. 

Again see: https://github.com/joeyklee/my-data-feelings/blob/master/public/index.html

**Comment by Khensura21** [comment]
Thanks, Joey! Sorry for the surplus of questions.

**Comment by joeyklee** [comment]
@Khensura21 - no need to apologize! We're working through all this together. I reckon it's tough stuff, but you got this!
