### ISSUE TITLE
P5 Geolocation Issues

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2019#18]
Hi All,

Some of you have reported that your geolocation isn't working which ends up breaking your entire code. You might have a look at this discussion here for some clarification what is going on: https://github.com/bmoren/p5.geolocation/issues/8

**Comment by stabriella** [comment]
I discovered the issue to be in my iOS system preferences -> security &
privacy -> location settings, which overrule whatever location settings you
have on your browser fyi..

**Comment by joeyklee** [comment]
@medusamachina brilliant! Thanks for flagging this!
