### ISSUE TITLE
[Final Project Proposals] Due April 1, 2019 

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2019#22]
Please submit your final project proposals in the comments below.

## Students
- [x] @evapphilips 
- [x] @Khensura21 
- [x] @sskripak 
- [x] @agudnason 
- [X] @reneereggler 
- [x] @mingnali7
- [x] @louiselessel
- [x] @js6450 
- [x] @kook101 
- [x] @deibid
- [x] @karihigh
- [x] @veroalfaro
- [x] @sl7211 
- [x] @medusamachina 
- [x] @joyantwi
- [X] Jacky

**Comment by js6450** [comment]
@js6450 
[Link to final project proposal](https://github.com/js6450/quantifiedHumanists/blob/master/assignments/final/proposal.md)

**Comment by stabriella** [comment]
@medusamachina
[Final Project Brief](https://github.com/joeyklee/quant-humanists-2019/blob/master/final-project.md)
[Link to final project proposal](https://www.higabriella.com/blog/quanthumanists-final-proposal-pleasure-principal)

**Comment by mingnali7** [comment]
[link to final proposal](https://www.mingnaliblog.com/quantified-humanists/2019/4/1/final-project-proposal)

**Comment by kook101** [comment]
Updated
[link](https://docs.google.com/presentation/d/1TlhYwxFF6ZzPr4BItnRfuKMD08Vcm7AQp4Tj1k2G-fA/edit?usp=sharing)

**Comment by karihigh** [comment]
@karihigh
[Project proposal](https://github.com/karihigh/s2_quanthumanists/blob/master/A_6_Final_project_propsal.md)

**Comment by louiselessel** [comment]
@louiselessel
[Project proposal](https://docs.google.com/presentation/d/1Ur1SFCzWpimk1nBJvkUBnGiRS5AsUA3xlPWAXxpiqMg/edit?usp=sharing)

**Comment by evapphilips** [comment]
[Project Proposal](https://drive.google.com/open?id=14tLDTOiEQhzQDrHIxuM7fb8cs32Q22xx)

[other link](https://drive.google.com/open?id=1Ot7pUQi6iUeCJuIOY_GZrlKQ-dQorwWc)

**Comment by veroalfaro** [comment]
[Final Project Proposal ](https://drive.google.com/open?id=1u1fMNd7Gy63ANz7aB9SEtxBAfHolqRGg)

**Comment by sskripak** [comment]
[Link to project proposal](https://www.stefanskripak.com/blog/2019/4/1/quantified-humanists-final-project-proposal)

**Comment by sl7211** [comment]
@sl7211

[Final Project Proposal Keynote](https://drive.google.com/file/d/1sZ9zmo3x3_AX0UTlWE6-S8MuiylkyGK_/view?usp=sharing)

**Comment by deibid** [comment]
Final Proposal Keynote -> [Go](https://drive.google.com/open?id=1MQZBkAfgihup5ia5Mcq1UR_52Pv_MP-L)

**Comment by Jackycqm** [comment]
<Jacky>

Link to slides: https://docs.google.com/presentation/d/1z0Y7NjS4eGgPIAaJqYlnlB99yPNJPAcpbIHPZcgoqdM/edit#slide=id.g50e0c374a8_0_110

**Comment by agudnason** [comment]
https://drive.google.com/file/d/1smsAP1Q-RJ68MTC4YsoPCv0KBlbD1x-W/view?usp=sharing

**Comment by reneereggler** [comment]
[Link to final project proposal ](http://www.iamreggler.com/2019/04/01/final-project-proposal/)

**Comment by Khensura21** [comment]
Link to [Final Project Proposal](https://docs.google.com/presentation/d/1GZ27_DOnQQOaEra4zgh8j_uNTmERYXmoGkRh_9YXRXU/edit#slide=id.p)

**Comment by joyantwi** [comment]
[Link to final proposal](https://docs.google.com/presentation/d/1ibjuIf_c-bzgfQlKNFqZ_S2GkVU1AhY8rAa3xwn6BDA/edit#slide=id.g5567acbdb3_0_10l)
