### ISSUE TITLE
 [Assignment #2] Dear Data Tracking & Visualization

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2019#8]
Please submit your Assignment 2 below in the comments structured as follows:

`<your username here>`
- **Link to Assignment Brief**: https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data
- **A2 -- Link to Dear Data Visualization and Reflection**: 🔗

## Students
- [x] @evapphilips 
- [x] @Khensura21 
- [x] @sskripak 
- [x] @agudnason 
- [x] @reneereggler 
- [x] @mingnali7
- [x] @louiselessel
- [x] @js6450 
- [x] @kook101 
- [x] @deibid
- [x] @karihigh
- [x] @veroalfaro
- [x] @sl7211 
- [x] @medusamachina 
- [X] @joyantwi
- [X] @Jackycqm

**Comment by Khensura21** [comment]
@Khensura21

* **Link to Assignment Brief**: https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data

* A2 -- [Link to Dear Data Visualization and Reflection**: ](https://itpkloveel.wordpress.com/2019/02/11/assignment-2-1-dear-data/)

**Comment by agudnason** [comment]
Blog + Assignment: https://www.annagudnason.com/blog/dear-data-quantified-humanists-week-2

**Comment by js6450** [comment]
@js6450 

A2 - [Dear Data Visualization and Reflection](https://github.com/js6450/quantifiedHumanists/blob/master/assignments/week2/dear-data.md)

**Comment by veroalfaro** [comment]
A2: [Veronica Dear Data Visualization and Reflection](https://www.veronica-alfaro.com/blog/2019/2/11/quantifying-data-a-week-in-compliments)

**Comment by louiselessel** [comment]
A2: [Dear Data postcard ](http://itp.louiselessel.com/2019/02/dear-data-postcard/)

**Comment by sskripak** [comment]
[Link to Assignment](https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data)
[A2: Dear Data Visualization](https://www.stefanskripak.com/blog/2019/2/11/quantified-humanists-assignment-2-dear-data)

**Comment by evapphilips** [comment]
* **Link to Assignment Brief**: https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data
* **A2 -- Link to Dear Data Visualization and Reflection**: https://www.evaphilips.com/quantified-humanist/2019/2/11/week-2-dear-data

**Comment by stabriella** [comment]
Gabriella Garcia
QUANT HUMANISTS 
SPRING 2019 
11 02 2019
[A2: Dear Data & first thoughts](https://www.higabriella.com/blog/quanthumanists-week-2-catching-up)
* **Link to Assignment Brief**: https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data

**Comment by mingnali7** [comment]
* **A2 -- Link to Dear Data Visualization and Reflection**: [🔗](https://www.mingnaliblog.com/quantified-humanists/2019/2/11/a2-dear-data-tracking-amp-reflection)

**Comment by karihigh** [comment]
@karihigh

[Link to documentation](https://github.com/karihigh/s2_quanthumanists/blob/master/A_2A.md)
[Link to reflection](https://github.com/karihigh/s2_quanthumanists/blob/master/A_2B.md)

**Comment by sl7211** [comment]
@sl7211

* [Assignment Brief](https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data)
* A2 -[Dear Data Visualization and Reflection](https://medium.com/suzanne-blog/suzanne-li-quant-humanists-spring-2019-09-02-2019-af90d92df7ce)

**Comment by kook101** [comment]
A2 - [Dear data](https://expandingexperience.kr/Week-2-Dear-Data)

**Comment by joyantwi** [comment]
[Assignment Brief](https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data)
[Assignment 2 - Dear Data Visualization & Reflection](https://joyantwi.com/quantified-humanist/)

**Comment by deibid** [comment]
Assignment 2 - [Dear Data](https://github.com/deibid/quantified-humanist/blob/master/week-2/Visualization%20of%20one%20week.md)

**Comment by reneereggler** [comment]
**Link to Assignment Brief**: [Dear Data](https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data)
**Assignment A.2**: [Dear Data Tracking & Visualization](https://www.iamreggler.com/2019/02/15/a-week-of-dawgs/)

**Comment by Jackycqm** [comment]
`<JackyCQM>`

* **Link to Assignment Brief**: https://github.com/joeyklee/quant-humanists-2019/blob/master/WEEK_02.md#assignment-2-due-week-03-11-feb-2019-dear-data
* **A2 -- Link to Dear Data Visualization and Reflection**: 🔗https://www.supersonichypnosis.com/#/quantified-humanists-design/
